spring:
  web:
    resources:
      add-mappings: false
  application:
    name: baba
  datasource:
    url: jdbc:h2:mem:baba-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  prefix: 'Bearer '
  secret-key: ${JWT}
  access-token-validity-in-seconds: 150
  refresh-token-validity-in-seconds: 259200
  access-header: Authentication
  refresh-header: Refresh

cookie:
  limit-time: 259200
  accepted-url: '/api/auth/reissue'
  cookie-name: Refresh
  domain: localhost